---

- hosts: all
  become: yes
  roles:
    - role: initdroid
      tags: init
    - role: node_exporter
      tags: monitoring

- hosts: kube-masters
  become: yes
  serial: 1
  roles:
    - role: k3s
      tags: k3s
    - role: get_node_token
      tags: k3s

- hosts: kube-workers
  become: yes
  serial: 1
  roles:
    - role: k3s
      tags: k3s

...
