---

- block:
    - name: Python is install
      apt:
        name: python
  rescue:
    - name: Install python
      raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400

- name: Set a pretty hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Ensure ansible user exists
  user:
    name: "{{ initdroid_ansible_user }}"
    state: present
    comment: Ansible
    shell: /bin/bash

- name: Enable including files from sudoers.d/
  lineinfile:
    path: "/etc/sudoers"
    regexp: "^#includedir /etc/sudoers.d"
    line: "#includedir /etc/sudoers.d"
    state: "present"
    backup: True

- name: Enable passwordless sudo
  copy:
    content: "%{{ initdroid_ansible_user }} ALL=(ALL) NOPASSWD:ALL"
    dest: "/etc/sudoers.d/{{ initdroid_ansible_user }}"
    owner: "root"
    group: "root"
    mode: "0440"

- name: Set authorized key from file
  authorized_key:
    user: "{{ initdroid_ansible_user }}"
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Disable root login
  lineinfile:
    path: "/etc/ssh/sshd_config"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: "present"
    backup: True
  notify: Restart sshd

- name: Update /etc/hosts with host address
  lineinfile:
    path: /etc/hosts
    line: "{{ ansible_default_ipv4.address }}    {{ inventory_hostname }}"

...
